
package client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.7-b01 
 * Generated source version: 2.2
 * 
 */
@WebService(name = "HelloWorld", targetNamespace = "http://helloworld/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface HelloWorld {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "Hello")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "Hello", targetNamespace = "http://helloworld/", className = "client.Hello")
    @ResponseWrapper(localName = "HelloResponse", targetNamespace = "http://helloworld/", className = "client.HelloResponse")
    @Action(input = "http://helloworld/HelloWorld/HelloRequest", output = "http://helloworld/HelloWorld/HelloResponse")
    public String hello(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns client.Foo
     */
    @WebMethod(operationName = "HelloFoo")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "HelloFoo", targetNamespace = "http://helloworld/", className = "client.HelloFoo")
    @ResponseWrapper(localName = "HelloFooResponse", targetNamespace = "http://helloworld/", className = "client.HelloFooResponse")
    @Action(input = "http://helloworld/HelloWorld/HelloFooRequest", output = "http://helloworld/HelloWorld/HelloFooResponse")
    public Foo helloFoo(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
