/*
 * Copyright (C) The Ambient Dynamix Project
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License. 
 */
package org.ambientdynamix.api.contextplugin;

import java.util.UUID;

/**
 * Interface for ContextPluginRuntime event listeners. This class is used by the Dynamix Framework internally to listen
 * to events generated by plug-ins.
 * 
 * @author Darren Carlson
 */
public interface IPluginContextListener {
	/**
	 * Callback method for handling context request failures.
	 * 
	 * @param sessionId
	 *            The sessionId of the ContextPluginRuntime generating the event data.
	 * @param requestId
	 *            The original requestId of the context request.
	 * @param errorMessage
	 *            The error message.
	 * @param errorCode
	 *            The error code.
	 */
	void onContextRequestFailed(UUID sessionId, UUID requestId, String errorMessage, int errorCode);

	/**
	 * Main callback method for handling SecuredEvents generated by ContextPluginRuntimes.
	 * 
	 * @param sessionId
	 *            The sessionId of the ContextPluginRuntime generating the event data.
	 * @param dataSet
	 *            The ContextDataSet associated with this event.
	 */
	void onPluginContextEvent(UUID sessionId, ContextInfoSet dataSet);
}